// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// CtfExchange events
        #[prost(message, tag="10")]
        CtfExchangeFeeCharged(super::CtfExchangeFeeCharged),
        #[prost(message, tag="11")]
        CtfExchangeNewAdmin(super::CtfExchangeNewAdmin),
        #[prost(message, tag="12")]
        CtfExchangeNewOperator(super::CtfExchangeNewOperator),
        #[prost(message, tag="13")]
        CtfExchangeOrderCancelled(super::CtfExchangeOrderCancelled),
        #[prost(message, tag="14")]
        CtfExchangeOrderFilled(super::CtfExchangeOrderFilled),
        #[prost(message, tag="15")]
        CtfExchangeOrdersMatched(super::CtfExchangeOrdersMatched),
        #[prost(message, tag="16")]
        CtfExchangeProxyFactoryUpdated(super::CtfExchangeProxyFactoryUpdated),
        #[prost(message, tag="17")]
        CtfExchangeRemovedAdmin(super::CtfExchangeRemovedAdmin),
        #[prost(message, tag="18")]
        CtfExchangeRemovedOperator(super::CtfExchangeRemovedOperator),
        #[prost(message, tag="19")]
        CtfExchangeSafeFactoryUpdated(super::CtfExchangeSafeFactoryUpdated),
        #[prost(message, tag="20")]
        CtfExchangeTokenRegistered(super::CtfExchangeTokenRegistered),
        #[prost(message, tag="21")]
        CtfExchangeTradingPaused(super::CtfExchangeTradingPaused),
        #[prost(message, tag="22")]
        CtfExchangeTradingUnpaused(super::CtfExchangeTradingUnpaused),
        #[prost(message, tag="23")]
        CtfExchangeFeeReceiverUpdated(super::CtfExchangeFeeReceiverUpdated),
        #[prost(message, tag="24")]
        CtfExchangeMaxFeeRateUpdated(super::CtfExchangeMaxFeeRateUpdated),
        #[prost(message, tag="25")]
        CtfExchangeOrderPreapproved(super::CtfExchangeOrderPreapproved),
        #[prost(message, tag="26")]
        CtfExchangeOrderPreapprovalInvalidated(super::CtfExchangeOrderPreapprovalInvalidated),
        #[prost(message, tag="27")]
        CtfExchangeUserPaused(super::CtfExchangeUserPaused),
        #[prost(message, tag="28")]
        CtfExchangeUserUnpaused(super::CtfExchangeUserUnpaused),
        #[prost(message, tag="29")]
        CtfExchangeUserPauseBlockIntervalUpdated(super::CtfExchangeUserPauseBlockIntervalUpdated),
        /// CollateralToken events
        #[prost(message, tag="30")]
        CollateralTokenWrapped(super::CollateralTokenWrapped),
        #[prost(message, tag="31")]
        CollateralTokenUnwrapped(super::CollateralTokenUnwrapped),
        /// ConditionalTokens events
        #[prost(message, tag="32")]
        ConditionalTokensConditionPreparation(super::ConditionalTokensConditionPreparation),
        #[prost(message, tag="33")]
        ConditionalTokensConditionResolution(super::ConditionalTokensConditionResolution),
        #[prost(message, tag="34")]
        ConditionalTokensPositionSplit(super::ConditionalTokensPositionSplit),
        #[prost(message, tag="35")]
        ConditionalTokensPositionsMerge(super::ConditionalTokensPositionsMerge),
        #[prost(message, tag="36")]
        ConditionalTokensPayoutRedemption(super::ConditionalTokensPayoutRedemption),
        /// FeeModule events
        #[prost(message, tag="37")]
        FeeModuleFeeRefunded(super::FeeModuleFeeRefunded),
        #[prost(message, tag="38")]
        FeeModuleFeeWithdrawn(super::FeeModuleFeeWithdrawn),
        #[prost(message, tag="39")]
        FeeModuleNewAdmin(super::FeeModuleNewAdmin),
        #[prost(message, tag="40")]
        FeeModuleRemovedAdmin(super::FeeModuleRemovedAdmin),
        /// NegRiskAdapter events
        #[prost(message, tag="41")]
        NegriskAdapterMarketPrepared(super::NegRiskAdapterMarketPrepared),
        #[prost(message, tag="42")]
        NegriskAdapterNewAdmin(super::NegRiskAdapterNewAdmin),
        #[prost(message, tag="43")]
        NegriskAdapterOutcomeReported(super::NegRiskAdapterOutcomeReported),
        #[prost(message, tag="44")]
        NegriskAdapterPayoutRedemption(super::NegRiskAdapterPayoutRedemption),
        #[prost(message, tag="45")]
        NegriskAdapterPositionSplit(super::NegRiskAdapterPositionSplit),
        #[prost(message, tag="46")]
        NegriskAdapterPositionsConverted(super::NegRiskAdapterPositionsConverted),
        #[prost(message, tag="47")]
        NegriskAdapterPositionsMerge(super::NegRiskAdapterPositionsMerge),
        #[prost(message, tag="48")]
        NegriskAdapterQuestionPrepared(super::NegRiskAdapterQuestionPrepared),
        #[prost(message, tag="49")]
        NegriskAdapterRemovedAdmin(super::NegRiskAdapterRemovedAdmin),
        /// SafeProxyFactory events
        #[prost(message, tag="50")]
        SafeProxyFactoryProxyCreation(super::SafeProxyFactoryProxyCreation),
        #[prost(message, tag="51")]
        SafeProxyFactoryProxyCreationL2(super::SafeProxyFactoryProxyCreationL2),
        #[prost(message, tag="52")]
        SafeProxyFactoryChainSpecificProxyCreationL2(super::SafeProxyFactoryChainSpecificProxyCreationL2),
        /// UmaCtfAdapter events
        #[prost(message, tag="53")]
        UmaCtfAdapterAncillaryDataUpdated(super::UmaCtfAdapterAncillaryDataUpdated),
        #[prost(message, tag="54")]
        UmaCtfAdapterNewAdmin(super::UmaCtfAdapterNewAdmin),
        #[prost(message, tag="55")]
        UmaCtfAdapterQuestionEmergencyResolved(super::UmaCtfAdapterQuestionEmergencyResolved),
        #[prost(message, tag="56")]
        UmaCtfAdapterQuestionFlagged(super::UmaCtfAdapterQuestionFlagged),
        #[prost(message, tag="57")]
        UmaCtfAdapterQuestionInitialized(super::UmaCtfAdapterQuestionInitialized),
        #[prost(message, tag="58")]
        UmaCtfAdapterQuestionPaused(super::UmaCtfAdapterQuestionPaused),
        #[prost(message, tag="59")]
        UmaCtfAdapterQuestionReset(super::UmaCtfAdapterQuestionReset),
        #[prost(message, tag="60")]
        UmaCtfAdapterQuestionResolved(super::UmaCtfAdapterQuestionResolved),
        #[prost(message, tag="61")]
        UmaCtfAdapterQuestionUnpaused(super::UmaCtfAdapterQuestionUnpaused),
        #[prost(message, tag="62")]
        UmaCtfAdapterRemovedAdmin(super::UmaCtfAdapterRemovedAdmin),
        #[prost(message, tag="63")]
        UmaCtfAdapterQuestionUnflagged(super::UmaCtfAdapterQuestionUnflagged),
    }
}
/// CtfExchange
/// <https://github.com/pinax-network/substreams-abis/blob/main/abi/evm/polymarket/CFTExchange.json>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeFeeCharged {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub receiver: ::prost::alloc::vec::Vec<u8>,
    /// uint256 (V1 only)
    #[prost(string, optional, tag="2")]
    pub token_id: ::core::option::Option<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeNewAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub new_admin_address: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeNewOperator {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub new_operator_address: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeOrderCancelled {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub order_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeOrderFilled {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub order_hash: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub maker: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="3")]
    pub taker: ::prost::alloc::vec::Vec<u8>,
    /// uint256 (V1 only)
    #[prost(string, optional, tag="4")]
    pub maker_asset_id: ::core::option::Option<::prost::alloc::string::String>,
    /// uint256 (V1 only)
    #[prost(string, optional, tag="5")]
    pub taker_asset_id: ::core::option::Option<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="6")]
    pub maker_amount_filled: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="7")]
    pub taker_amount_filled: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="8")]
    pub fee: ::prost::alloc::string::String,
    /// uint8 (V2 only)
    #[prost(uint32, optional, tag="9")]
    pub side: ::core::option::Option<u32>,
    /// uint256 (V2 only)
    #[prost(string, optional, tag="10")]
    pub token_id: ::core::option::Option<::prost::alloc::string::String>,
    /// bytes32 (V2 only)
    #[prost(bytes="vec", optional, tag="11")]
    pub builder: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// bytes32 (V2 only)
    #[prost(bytes="vec", optional, tag="12")]
    pub metadata: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeOrdersMatched {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub taker_order_hash: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub taker_order_maker: ::prost::alloc::vec::Vec<u8>,
    /// uint256 (V1 only)
    #[prost(string, optional, tag="3")]
    pub maker_asset_id: ::core::option::Option<::prost::alloc::string::String>,
    /// uint256 (V1 only)
    #[prost(string, optional, tag="4")]
    pub taker_asset_id: ::core::option::Option<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="5")]
    pub maker_amount_filled: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="6")]
    pub taker_amount_filled: ::prost::alloc::string::String,
    /// uint8 (V2 only)
    #[prost(uint32, optional, tag="7")]
    pub side: ::core::option::Option<u32>,
    /// uint256 (V2 only)
    #[prost(string, optional, tag="8")]
    pub token_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeProxyFactoryUpdated {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub old_proxy_factory: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub new_proxy_factory: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeRemovedAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub removed_admin: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeRemovedOperator {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub removed_operator: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeSafeFactoryUpdated {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub old_safe_factory: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub new_safe_factory: ::prost::alloc::vec::Vec<u8>,
}
/// key = <bytes32 conditionId>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeTokenRegistered {
    /// STORE primary key
    ///
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub token0: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub token1: ::prost::alloc::string::String,
}
/// StoreToken - minimal token storage type
/// Primary key: conditionId
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeTradingPaused {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub pauser: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeTradingUnpaused {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub pauser: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeFeeReceiverUpdated {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub fee_receiver: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeMaxFeeRateUpdated {
    /// uint256
    #[prost(string, tag="1")]
    pub max_fee_rate: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeOrderPreapproved {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub order_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeOrderPreapprovalInvalidated {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub order_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeUserPaused {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub effective_pause_block: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeUserUnpaused {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub user: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CtfExchangeUserPauseBlockIntervalUpdated {
    /// uint256
    #[prost(string, tag="1")]
    pub old_interval: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub new_interval: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollateralTokenWrapped {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub asset: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="3")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollateralTokenUnwrapped {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub asset: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="3")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
}
/// ConditionalTokens
/// ConditionalTokens events (excluding ERC1155 standard events)
/// <https://github.com/gnosis/conditional-tokens-contracts>
/// ConditionPreparation event
/// Emitted upon the successful preparation of a condition
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConditionalTokensConditionPreparation {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub oracle: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="3")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="4")]
    pub outcome_slot_count: ::prost::alloc::string::String,
}
/// ConditionResolution event
/// Emitted when a condition is resolved
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConditionalTokensConditionResolution {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub oracle: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="3")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="4")]
    pub outcome_slot_count: ::prost::alloc::string::String,
    /// uint256\[\]
    #[prost(string, repeated, tag="5")]
    pub payout_numerators: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// PositionSplit event
/// Emitted when a position is successfully split
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConditionalTokensPositionSplit {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub stakeholder: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub collateral_token: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="3")]
    pub parent_collection_id: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="4")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[\]
    #[prost(string, repeated, tag="5")]
    pub partition: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
}
/// PositionsMerge event
/// Emitted when positions are successfully merged
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConditionalTokensPositionsMerge {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub stakeholder: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub collateral_token: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="3")]
    pub parent_collection_id: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="4")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[\]
    #[prost(string, repeated, tag="5")]
    pub partition: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
}
/// PayoutRedemption event
/// Emitted when payout is redeemed
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConditionalTokensPayoutRedemption {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub redeemer: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub collateral_token: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="3")]
    pub parent_collection_id: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="4")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[\]
    #[prost(string, repeated, tag="5")]
    pub index_sets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="6")]
    pub payout: ::prost::alloc::string::String,
}
/// FeeModule
/// FeeModule events
/// FeeRefunded event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeModuleFeeRefunded {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub order_hash: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub refund: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub fee_charged: ::prost::alloc::string::String,
}
/// FeeWithdrawn event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeModuleFeeWithdrawn {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
}
/// NewAdmin event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeModuleNewAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub new_admin_address: ::prost::alloc::vec::Vec<u8>,
}
/// RemovedAdmin event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeModuleRemovedAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub removed_admin: ::prost::alloc::vec::Vec<u8>,
}
/// NegRiskAdapter
/// NegRiskAdapter events
/// MarketPrepared event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NegRiskAdapterMarketPrepared {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub oracle: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub fee_bips: ::prost::alloc::string::String,
    /// bytes
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// NewAdmin event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NegRiskAdapterNewAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub new_admin_address: ::prost::alloc::vec::Vec<u8>,
}
/// OutcomeReported event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NegRiskAdapterOutcomeReported {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// bool
    #[prost(bool, tag="3")]
    pub outcome: bool,
}
/// PayoutRedemption event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NegRiskAdapterPayoutRedemption {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub redeemer: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[\]
    #[prost(string, repeated, tag="3")]
    pub amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="4")]
    pub payout: ::prost::alloc::string::String,
}
/// PositionSplit event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NegRiskAdapterPositionSplit {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub stakeholder: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
/// PositionsConverted event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NegRiskAdapterPositionsConverted {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub stakeholder: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub index_set: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
}
/// PositionsMerge event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NegRiskAdapterPositionsMerge {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub stakeholder: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
/// QuestionPrepared event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NegRiskAdapterQuestionPrepared {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub index: ::prost::alloc::string::String,
    /// bytes
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// RemovedAdmin event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NegRiskAdapterRemovedAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub removed_admin: ::prost::alloc::vec::Vec<u8>,
}
/// SafeProxyFactory
/// <https://github.com/safe-global/safe-contracts/blob/main/contracts/proxies/SafeProxyFactory.sol>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SafeProxyFactoryProxyCreation {
    /// address
    #[prost(bytes="vec", tag="10")]
    pub proxy: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="11")]
    pub singleton: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SafeProxyFactoryProxyCreationL2 {
    /// address
    #[prost(bytes="vec", tag="10")]
    pub proxy: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="11")]
    pub singleton: ::prost::alloc::vec::Vec<u8>,
    /// bytes
    #[prost(bytes="vec", tag="12")]
    pub initializer: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="13")]
    pub salt_nonce: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SafeProxyFactoryChainSpecificProxyCreationL2 {
    /// address
    #[prost(bytes="vec", tag="10")]
    pub proxy: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="11")]
    pub singleton: ::prost::alloc::vec::Vec<u8>,
    /// bytes
    #[prost(bytes="vec", tag="12")]
    pub initializer: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="13")]
    pub salt_nonce: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="14")]
    pub chain_id: ::prost::alloc::string::String,
}
/// UmaCtfAdapter
/// UmaCtfAdapter events (V2 & V3 combined)
/// AncillaryDataUpdated event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmaCtfAdapterAncillaryDataUpdated {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    /// bytes
    #[prost(bytes="vec", tag="3")]
    pub update: ::prost::alloc::vec::Vec<u8>,
}
/// NewAdmin event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmaCtfAdapterNewAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub new_admin_address: ::prost::alloc::vec::Vec<u8>,
}
/// QuestionEmergencyResolved event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmaCtfAdapterQuestionEmergencyResolved {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[\]
    #[prost(string, repeated, tag="2")]
    pub payouts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// QuestionFlagged event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmaCtfAdapterQuestionFlagged {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
}
/// QuestionInitialized event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmaCtfAdapterQuestionInitialized {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub request_timestamp: ::prost::alloc::string::String,
    /// address
    #[prost(bytes="vec", tag="3")]
    pub creator: ::prost::alloc::vec::Vec<u8>,
    /// bytes
    #[prost(bytes="vec", tag="4")]
    pub ancillary_data: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="5")]
    pub reward_token: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="6")]
    pub reward: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="7")]
    pub proposal_bond: ::prost::alloc::string::String,
}
/// QuestionPaused event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmaCtfAdapterQuestionPaused {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
}
/// QuestionReset event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmaCtfAdapterQuestionReset {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
}
/// QuestionResolved event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmaCtfAdapterQuestionResolved {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// int256
    #[prost(string, tag="2")]
    pub settled_price: ::prost::alloc::string::String,
    /// uint256\[\]
    #[prost(string, repeated, tag="3")]
    pub payouts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// QuestionUnpaused event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmaCtfAdapterQuestionUnpaused {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
}
/// RemovedAdmin event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmaCtfAdapterRemovedAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub removed_admin: ::prost::alloc::vec::Vec<u8>,
}
/// QuestionUnflagged event (V3 only)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UmaCtfAdapterQuestionUnflagged {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
