[package]
name = "conditionaltokens"
description = "ConditionalTokens events substreams package"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
substreams = { workspace = true }
substreams-ethereum = { workspace = true }
proto = { path = "../proto" }
common = { path = "../common" }
hex-literal = "0.4"
primitive-types = "0.12"
