// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// ConditionalTokens events (excluding ERC1155 standard events)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 14")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// ConditionalTokens events
        #[prost(message, tag="10")]
        ConditionPreparation(super::ConditionPreparation),
        #[prost(message, tag="11")]
        ConditionResolution(super::ConditionResolution),
        #[prost(message, tag="12")]
        PositionSplit(super::PositionSplit),
        #[prost(message, tag="13")]
        PositionsMerge(super::PositionsMerge),
        #[prost(message, tag="14")]
        PayoutRedemption(super::PayoutRedemption),
    }
}
/// ConditionPreparation event
/// Emitted upon the successful preparation of a condition
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConditionPreparation {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub oracle: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="3")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="4")]
    pub outcome_slot_count: ::prost::alloc::string::String,
}
/// ConditionResolution event
/// Emitted when a condition is resolved
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConditionResolution {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub oracle: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="3")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="4")]
    pub outcome_slot_count: ::prost::alloc::string::String,
    /// uint256\[\]
    #[prost(string, repeated, tag="5")]
    pub payout_numerators: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// PositionSplit event
/// Emitted when a position is successfully split
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionSplit {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub stakeholder: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub collateral_token: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="3")]
    pub parent_collection_id: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="4")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[\]
    #[prost(string, repeated, tag="5")]
    pub partition: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
}
/// PositionsMerge event
/// Emitted when positions are successfully merged
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionsMerge {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub stakeholder: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub collateral_token: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="3")]
    pub parent_collection_id: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="4")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[\]
    #[prost(string, repeated, tag="5")]
    pub partition: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
}
/// PayoutRedemption event
/// Emitted when payout is redeemed
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayoutRedemption {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub redeemer: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub collateral_token: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="3")]
    pub parent_collection_id: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="4")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[\]
    #[prost(string, repeated, tag="5")]
    pub index_sets: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="6")]
    pub payout: ::prost::alloc::string::String,
}
