// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// ERC-20 events
        #[prost(message, tag="10")]
        Transfer(super::Transfer),
        #[prost(message, tag="11")]
        Approval(super::Approval),
        /// WETH events
        #[prost(message, tag="12")]
        Deposit(super::Deposit),
        #[prost(message, tag="13")]
        Withdrawal(super::Withdrawal),
    }
}
/// ERC-20 Transfer event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
/// ERC-20 Approval event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Approval {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub spender: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
}
/// WETH Deposit event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deposit {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub dst: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub wad: ::prost::alloc::string::String,
}
/// WETH Withdrawal event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Withdrawal {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub src: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub wad: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
