// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub balances: ::prost::alloc::vec::Vec<Balance>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Balance {
    /// log.address (`None` for native balances)
    #[prost(bytes="vec", optional, tag="1")]
    pub contract: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="2")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// balanceOf(address account) -> uint256
    #[prost(string, tag="3")]
    pub balance: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
