// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// NegRiskAdapter events
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 14, 15, 16, 17, 18")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// NegRiskAdapter events
        #[prost(message, tag="10")]
        MarketPrepared(super::MarketPrepared),
        #[prost(message, tag="11")]
        NewAdmin(super::NewAdmin),
        #[prost(message, tag="12")]
        OutcomeReported(super::OutcomeReported),
        #[prost(message, tag="13")]
        PayoutRedemption(super::PayoutRedemption),
        #[prost(message, tag="14")]
        PositionSplit(super::PositionSplit),
        #[prost(message, tag="15")]
        PositionsConverted(super::PositionsConverted),
        #[prost(message, tag="16")]
        PositionsMerge(super::PositionsMerge),
        #[prost(message, tag="17")]
        QuestionPrepared(super::QuestionPrepared),
        #[prost(message, tag="18")]
        RemovedAdmin(super::RemovedAdmin),
    }
}
/// MarketPrepared event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketPrepared {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub oracle: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub fee_bips: ::prost::alloc::string::String,
    /// bytes
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// NewAdmin event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub new_admin_address: ::prost::alloc::vec::Vec<u8>,
}
/// OutcomeReported event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OutcomeReported {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// bool
    #[prost(bool, tag="3")]
    pub outcome: bool,
}
/// PayoutRedemption event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayoutRedemption {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub redeemer: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[\]
    #[prost(string, repeated, tag="3")]
    pub amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="4")]
    pub payout: ::prost::alloc::string::String,
}
/// PositionSplit event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionSplit {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub stakeholder: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
/// PositionsConverted event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionsConverted {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub stakeholder: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub index_set: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
}
/// PositionsMerge event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionsMerge {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub stakeholder: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
/// QuestionPrepared event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QuestionPrepared {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub market_id: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes="vec", tag="2")]
    pub question_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub index: ::prost::alloc::string::String,
    /// bytes
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// RemovedAdmin event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemovedAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub removed_admin: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
