// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// <https://github.com/pinax-network/substreams-abis/blob/main/abi/evm/polymarket/CFTExchange.json>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// CFTExchange events
        #[prost(message, tag="10")]
        FeeCharged(super::FeeCharged),
        #[prost(message, tag="11")]
        NewAdmin(super::NewAdmin),
        #[prost(message, tag="12")]
        NewOperator(super::NewOperator),
        #[prost(message, tag="13")]
        OrderCancelled(super::OrderCancelled),
        #[prost(message, tag="14")]
        OrderFilled(super::OrderFilled),
        #[prost(message, tag="15")]
        OrdersMatched(super::OrdersMatched),
        #[prost(message, tag="16")]
        ProxyFactoryUpdated(super::ProxyFactoryUpdated),
        #[prost(message, tag="17")]
        RemovedAdmin(super::RemovedAdmin),
        #[prost(message, tag="18")]
        RemovedOperator(super::RemovedOperator),
        #[prost(message, tag="19")]
        SafeFactoryUpdated(super::SafeFactoryUpdated),
        #[prost(message, tag="20")]
        TokenRegistered(super::TokenRegistered),
        #[prost(message, tag="21")]
        TradingPaused(super::TradingPaused),
        #[prost(message, tag="22")]
        TradingUnpaused(super::TradingUnpaused),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeCharged {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub receiver: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub token_id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub new_admin_address: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewOperator {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub new_operator_address: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderCancelled {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub order_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderFilled {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub order_hash: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub maker: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="3")]
    pub taker: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="4")]
    pub maker_asset_id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub taker_asset_id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="6")]
    pub maker_amount_filled: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="7")]
    pub taker_amount_filled: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="8")]
    pub fee: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrdersMatched {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub taker_order_hash: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub taker_order_maker: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub maker_asset_id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub taker_asset_id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub maker_amount_filled: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="6")]
    pub taker_amount_filled: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProxyFactoryUpdated {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub old_proxy_factory: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub new_proxy_factory: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemovedAdmin {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub removed_admin: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemovedOperator {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub removed_operator: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SafeFactoryUpdated {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub old_safe_factory: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub new_safe_factory: ::prost::alloc::vec::Vec<u8>,
}
/// key = <bytes32 conditionId>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenRegistered {
    /// STORE primary key
    ///
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub condition_id: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub token0: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub token1: ::prost::alloc::string::String,
}
/// StoreToken - minimal token storage type
/// Primary key: conditionId
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StoreToken {
    /// uint256 token ID
    #[prost(string, tag="1")]
    pub token0: ::prost::alloc::string::String,
    /// uint256 token ID
    #[prost(string, tag="2")]
    pub token1: ::prost::alloc::string::String,
    /// exchange address that registered the token
    #[prost(bytes="vec", tag="3")]
    pub exchange: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradingPaused {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub pauser: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradingUnpaused {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub pauser: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
