// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// https://github.com/safe-global/safe-contracts/blob/main/contracts/proxies/SafeProxyFactory.sol
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="10, 11, 12")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// events
        #[prost(message, tag="10")]
        ProxyCreation(super::ProxyCreation),
        #[prost(message, tag="11")]
        ProxyCreationL2(super::ProxyCreationL2),
        #[prost(message, tag="12")]
        ChainSpecificProxyCreationL2(super::ChainSpecificProxyCreationL2),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProxyCreation {
    /// address
    #[prost(bytes="vec", tag="10")]
    pub proxy: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="11")]
    pub singleton: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProxyCreationL2 {
    /// address
    #[prost(bytes="vec", tag="10")]
    pub proxy: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="11")]
    pub singleton: ::prost::alloc::vec::Vec<u8>,
    /// bytes
    #[prost(bytes="vec", tag="12")]
    pub initializer: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="13")]
    pub salt_nonce: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChainSpecificProxyCreationL2 {
    /// address
    #[prost(bytes="vec", tag="10")]
    pub proxy: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="11")]
    pub singleton: ::prost::alloc::vec::Vec<u8>,
    /// bytes
    #[prost(bytes="vec", tag="12")]
    pub initializer: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="13")]
    pub salt_nonce: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="14")]
    pub chain_id: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
