syntax = "proto3";

package fpmm.v1;

message Events { repeated Transaction transactions = 1; }

message Transaction {
  bytes hash = 1;
  bytes from = 2;
  optional bytes to = 3;
  uint64 nonce = 5;
  string gas_price = 6; // uint256
  uint64 gas_limit = 7;
  uint64 gas_used = 8;
  string value = 9; // uint256
  repeated Log logs = 10;
}

// FixedProductMarketMaker events
message Log {
  bytes address = 1;
  uint64 ordinal = 2;
  repeated bytes topics = 3;
  bytes data = 4;
  oneof log {
    // FPMM events
    FPMMFundingAdded fpmm_funding_added = 10;
    FPMMFundingRemoved fpmm_funding_removed = 11;
    FPMMBuy fpmm_buy = 12;
    FPMMSell fpmm_sell = 13;
    Transfer transfer = 14;
    Approval approval = 15;
  }
}

// FPMMFundingAdded event
message FPMMFundingAdded {
  bytes funder = 1; // address (indexed)
  repeated string amounts_added = 2; // uint256[]
  string shares_minted = 3; // uint256
}

// FPMMFundingRemoved event
message FPMMFundingRemoved {
  bytes funder = 1; // address (indexed)
  repeated string amounts_removed = 2; // uint256[]
  string collateral_removed_from_fee_pool = 3; // uint256
  string shares_burnt = 4; // uint256
}

// FPMMBuy event
message FPMMBuy {
  bytes buyer = 1; // address (indexed)
  string investment_amount = 2; // uint256
  string fee_amount = 3; // uint256
  string outcome_index = 4; // uint256 (indexed)
  string outcome_tokens_bought = 5; // uint256
}

// FPMMSell event
message FPMMSell {
  bytes seller = 1; // address (indexed)
  string return_amount = 2; // uint256
  string fee_amount = 3; // uint256
  string outcome_index = 4; // uint256 (indexed)
  string outcome_tokens_sold = 5; // uint256
}

// Transfer event (ERC20)
message Transfer {
  bytes from = 1; // address (indexed)
  bytes to = 2; // address (indexed)
  string value = 3; // uint256
}

// Approval event (ERC20)
message Approval {
  bytes owner = 1; // address (indexed)
  bytes spender = 2; // address (indexed)
  string value = 3; // uint256
}
