syntax = "proto3";

package negriskadapter.v1;

message Events { repeated Transaction transactions = 1; }

message Transaction {
  bytes hash = 1;
  bytes from = 2;
  optional bytes to = 3;
  uint64 nonce = 5;
  string gas_price = 6; // uint256
  uint64 gas_limit = 7;
  uint64 gas_used = 8;
  string value = 9; // uint256
  repeated Log logs = 10;
}

// NegRiskAdapter events
message Log {
  bytes address = 1;
  uint64 ordinal = 2;
  repeated bytes topics = 3;
  bytes data = 4;
  oneof log {
    // NegRiskAdapter events
    MarketPrepared market_prepared = 10;
    NewAdmin new_admin = 11;
    OutcomeReported outcome_reported = 12;
    PayoutRedemption payout_redemption = 13;
    PositionSplit position_split = 14;
    PositionsConverted positions_converted = 15;
    PositionsMerge positions_merge = 16;
    QuestionPrepared question_prepared = 17;
    RemovedAdmin removed_admin = 18;
  }
}

// MarketPrepared event
message MarketPrepared {
  bytes market_id = 1; // bytes32
  bytes oracle = 2; // address
  string fee_bips = 3; // uint256
  bytes data = 4; // bytes
}

// NewAdmin event
message NewAdmin {
  bytes admin = 1; // address
  bytes new_admin_address = 2; // address
}

// OutcomeReported event
message OutcomeReported {
  bytes market_id = 1; // bytes32
  bytes question_id = 2; // bytes32
  bool outcome = 3; // bool
}

// PayoutRedemption event
message PayoutRedemption {
  bytes redeemer = 1; // address
  bytes condition_id = 2; // bytes32
  repeated string amounts = 3; // uint256[]
  string payout = 4; // uint256
}

// PositionSplit event
message PositionSplit {
  bytes stakeholder = 1; // address
  bytes condition_id = 2; // bytes32
  string amount = 3; // uint256
}

// PositionsConverted event
message PositionsConverted {
  bytes stakeholder = 1; // address
  bytes market_id = 2; // bytes32
  string index_set = 3; // uint256
  string amount = 4; // uint256
}

// PositionsMerge event
message PositionsMerge {
  bytes stakeholder = 1; // address
  bytes condition_id = 2; // bytes32
  string amount = 3; // uint256
}

// QuestionPrepared event
message QuestionPrepared {
  bytes market_id = 1; // bytes32
  bytes question_id = 2; // bytes32
  string index = 3; // uint256
  bytes data = 4; // bytes
}

// RemovedAdmin event
message RemovedAdmin {
  bytes admin = 1; // address
  bytes removed_admin = 2; // address
}
