syntax = "proto3";

package safeproxyfactory.v1;

message Events { repeated Transaction transactions = 1; }

message Transaction {
  bytes hash = 1;
  bytes from = 2;
  optional bytes to = 3;
  uint64 nonce = 5;
  string gas_price = 6; // uint256
  uint64 gas_limit = 7;
  uint64 gas_used = 8;
  string value = 9; // uint256
  repeated Log logs = 10;
}

// SafeProxyFactory events
// https://github.com/gnosis/safe-smart-account
message Log {
  bytes address = 1;
  uint64 ordinal = 2;
  repeated bytes topics = 3;
  bytes data = 4;
  oneof log {
    // events
    ProxyCreation proxy_creation = 10;
  }
}

// ProxyCreation event
// Emitted when a new Safe proxy is created
message ProxyCreation {
  bytes proxy = 1; // address - The address of the created proxy
  bytes owner = 2; // address - The owner of the created proxy
}
